# Generated by Django 3.0.5 on 2020-05-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentName', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
    ]
