# Generated by Django 3.0.5 on 2020-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venueImageName',
            new_name='VenueImageName',
        ),
        migrations.AlterField(
            model_name='venue',
            name='VenueId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
