# Generated by Django 3.0.5 on 2020-08-05 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=10)),
                ('EmployeeImageName', models.TextField(blank=True, null=True)),
                ('EmployeeImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('EmployeePhone', models.CharField(max_length=150)),
                ('EmployeeEmail', models.EmailField(blank=True, max_length=150, null=True)),
                ('EmployeeAddress', models.TextField()),
                ('EmployeeCity', models.CharField(max_length=150)),
                ('EmployeeStatus', models.BooleanField(default=False)),
                ('Role', models.CharField(default='staff', max_length=150)),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('SubDepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.SubDepartment')),
                ('UserId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
