# Generated by Django 3.0.6 on 2020-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Role',
            field=models.CharField(default='staff', max_length=150),
        ),
    ]
