# Generated by Django 3.0.7 on 2020-06-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificationTitle', models.TextField()),
                ('NotificationName', models.TextField()),
                ('NotificationDescription', models.TextField()),
                ('NotificationDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
