# Generated by Django 3.0.5 on 2020-06-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('NotificationName', models.TextField()),
                ('NotificationDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
