# Generated by Django 3.0.5 on 2020-06-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='NotificationName',
            new_name='NotificationDescription',
        ),
        migrations.AddField(
            model_name='notification',
            name='NotificationTitle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
