# Generated by Django 3.0.5 on 2020-06-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200616_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='NotificationName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
