# Generated by Django 3.0.5 on 2020-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='EventImageName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
