# Generated by Django 3.0.5 on 2020-06-14 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_remove_club_facebook'),
        ('venue', '0002_auto_20200519_1519'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ClubName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='EventAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='EventApproval',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='EventDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='EventEligibility',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='EventEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 14, 12, 30, 35, 415443, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='EventImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='EventImageName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 14, 12, 30, 35, 415443, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='EventStatus',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='EventType',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='VenueId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venue.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
