# Generated by Django 3.0.5 on 2020-06-15 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 15, 11, 29, 56, 221147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 15, 11, 29, 56, 221147, tzinfo=utc)),
        ),
    ]
