# Generated by Django 3.0.5 on 2020-05-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200519_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventApproval',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStatus',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
