# Generated by Django 3.0.5 on 2020-05-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20200519_1519'),
        ('event', '0003_auto_20200519_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='VenueId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venue.Venue'),
            preserve_default=False,
        ),
    ]
