# Generated by Django 3.0.5 on 2020-06-14 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200614_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 14, 17, 29, 31, 989507, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 14, 17, 29, 31, 989507, tzinfo=utc)),
        ),
    ]
