# Generated by Django 3.0.7 on 2020-06-20 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200620_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 20, 13, 14, 21, 771836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 20, 13, 14, 21, 771836, tzinfo=utc)),
        ),
    ]
