# Generated by Django 3.0.5 on 2020-05-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_subdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=150)),
                ('EmployeeUserName', models.CharField(max_length=150)),
                ('EmployeePassword', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=10)),
                ('EmployeeImage', models.ImageField(upload_to='employee')),
                ('EmployeePhone', models.CharField(max_length=150)),
                ('EmployeeEmail', models.EmailField(blank=True, max_length=150, null=True)),
                ('EmployeeAddress', models.TextField()),
                ('EmployeeCity', models.CharField(max_length=150)),
                ('EmployeeStatus', models.BooleanField(default=False)),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('SubDepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.SubDepartment')),
            ],
        ),
    ]
