# Generated by Django 3.0.5 on 2020-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200518_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmployeeImageName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
