# Generated by Django 3.0.5 on 2020-05-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_employee_employeeimagename'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAdmin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('AdminUserName', models.CharField(max_length=150)),
                ('AdminPassword', models.CharField(max_length=150)),
                ('AdminType', models.CharField(max_length=150)),
                ('Status', models.BooleanField()),
                ('EmployeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
