# Generated by Django 3.0.5 on 2020-08-05 04:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
        ('club', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('EventImageName', models.TextField(blank=True, null=True)),
                ('EventImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('EventType', models.CharField(max_length=150)),
                ('EventEligibility', models.CharField(max_length=150)),
                ('EventStatus', models.CharField(default=False, max_length=10)),
                ('EventApproval', models.CharField(default=-1, max_length=10)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('EventStartTime', models.TimeField(default=datetime.datetime(2020, 8, 5, 4, 7, 10, 290845, tzinfo=utc))),
                ('EventEndTime', models.TimeField(default=datetime.datetime(2020, 8, 5, 4, 7, 10, 290845, tzinfo=utc))),
                ('EventDescription', models.TextField()),
                ('EventAmount', models.IntegerField()),
                ('ClubName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
                ('VenueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('EventMemberId', models.AutoField(primary_key=True, serialize=False)),
                ('EventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventName', to='event.Event')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
