# Generated by Django 3.0.5 on 2020-06-25 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('event', '0003_auto_20200625_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 25, 6, 33, 55, 609100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 25, 6, 33, 55, 609100, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('EventMemberId', models.AutoField(primary_key=True, serialize=False)),
                ('EventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventName', to='event.Event')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
