# Generated by Django 3.0.7 on 2020-06-24 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200624_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 24, 10, 31, 30, 244948, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 6, 24, 10, 31, 30, 244948, tzinfo=utc)),
        ),
    ]
