# Generated by Django 3.0.6 on 2020-08-19 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200818_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 19, 6, 5, 21, 767959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 19, 6, 5, 21, 767959, tzinfo=utc)),
        ),
    ]
