# Generated by Django 3.0.6 on 2020-08-19 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200819_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventApproval',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 19, 12, 58, 48, 877873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStartTime',
            field=models.TimeField(default=datetime.datetime(2020, 8, 19, 12, 58, 48, 877873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventStatus',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
