# Generated by Django 3.0.5 on 2020-05-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeId', models.AutoField(primary_key=True, serialize=False)),
                ('CollegeName', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=150)),
                ('CollegeType', models.CharField(max_length=150)),
            ],
        ),
    ]
