# Generated by Django 3.0.7 on 2020-06-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20200620_1205'),
        ('department', '0002_subdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AchievementName', models.CharField(max_length=150)),
                ('AchievementDescription', models.TextField()),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('SubDepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.SubDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AchievementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
