# Generated by Django 3.0.5 on 2020-06-15 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('achievement', '0002_auto_20200519_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('AchieverId', models.AutoField(primary_key=True, serialize=False)),
                ('AchievementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.Achievement')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
