# Generated by Django 3.0.5 on 2020-05-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200518_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='clubApproval',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='clubStatus',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
