# Generated by Django 3.0.5 on 2020-05-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200518_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='DribberLink',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='FacebookLink',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='InstagramLink',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='TwitterLink',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='ClubType',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
