# Generated by Django 3.0.5 on 2020-05-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20200519_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='DribberLink',
            new_name='DribbbleLink',
        ),
    ]
