# Generated by Django 3.0.5 on 2020-05-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20200519_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='Facebook',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
