# Generated by Django 3.0.5 on 2020-05-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='Facebook',
        ),
    ]
