# Generated by Django 3.0.5 on 2020-06-15 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('club', '0008_remove_club_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('ClubMemberId', models.AutoField(primary_key=True, serialize=False)),
                ('MemberRole', models.CharField(max_length=150)),
                ('ClubId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
