# Generated by Django 3.0.7 on 2020-06-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_clubmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='ClubId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubName', to='club.Club'),
        ),
    ]
