# Generated by Django 3.0.5 on 2020-06-24 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=150)),
                ('StudentPhoneNumber', models.CharField(max_length=150)),
                ('StudentGender', models.CharField(max_length=10)),
                ('StudentImageName', models.TextField(blank=True, null=True)),
                ('StudentImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('StudentEmail', models.EmailField(blank=True, max_length=150, null=True)),
                ('StudentAddress', models.TextField()),
                ('StudentCity', models.CharField(max_length=150)),
                ('StudentStatus', models.BooleanField(default=False)),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('SubDepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.SubDepartment')),
                ('UserId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
