# Generated by Django 3.0.5 on 2020-08-05 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('ClubName', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('ClubImageName', models.TextField(blank=True, null=True)),
                ('ClubImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ClubType', models.CharField(blank=True, max_length=150, null=True)),
                ('FacebookLink', models.CharField(blank=True, max_length=150, null=True)),
                ('InstagramLink', models.CharField(blank=True, max_length=150, null=True)),
                ('TwitterLink', models.CharField(blank=True, max_length=150, null=True)),
                ('DribbbleLink', models.CharField(blank=True, max_length=150, null=True)),
                ('clubStatus', models.CharField(default=True, max_length=10)),
                ('clubApproval', models.CharField(default=1, max_length=10)),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('UserId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(blank=True, max_length=150, null=True)),
                ('ClubUserName', models.CharField(blank=True, max_length=150, null=True)),
                ('ClubPassword', models.CharField(blank=True, max_length=150, null=True)),
                ('ClubEmail', models.CharField(blank=True, max_length=150, null=True)),
                ('ClubImageName', models.TextField(blank=True, null=True)),
                ('ClubImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ClubType', models.CharField(blank=True, max_length=150, null=True)),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('StudentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('ClubMemberId', models.AutoField(primary_key=True, serialize=False)),
                ('MemberRole', models.CharField(max_length=150)),
                ('ClubId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubName', to='club.Club')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
