# Generated by Django 3.0.6 on 2020-08-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_clubmemberrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='clubApproval',
        ),
    ]
